"""
Created by Xuejian Ma at 6/18/2020.
All rights reserved.

This file is for reading saed conductivities generated by onver2Conductivities.py
"""
from utils import readConductivity,readImRe
from config import fileNameIm,fileNameRe,folderPathList,naiveScale
import numpy as np

im_img_all = []; re_img_all = [];
conductivity_all = []
for ind,folderPath in enumerate(folderPathList):
    conductivity_all.append(np.asarray(readConductivity(folderPath)))
    im_img_array,re_img_array = readImRe(folderPath, fileNameIm, fileNameRe, naiveScale)
    im_img_all.append(np.asarray(im_img_array))
    re_img_all.append(np.asarray(re_img_array))

# ind=5
# plt.pcolormesh(re_img_all[ind])
